name: CI Check

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest

    env:
      GROQ_API_KEY: dummy_key_for_ci

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.12"

      - name: Upgrade pip
        run: python -m pip install --upgrade pip

      - name: Install dependencies
        run: pip install -r requirements.txt

      - name: Check Python files
        run: |
          python -m py_compile app.py
          python -m py_compile src/config.py
          python -m py_compile src/transcript.py
          python -m py_compile src/chunker.py
          python -m py_compile src/summarizer.py
          python -m py_compile src/rag.py
          python -m py_compile src/pdf_generator.py
          python -m py_compile src/video_metadata.py
          python -m py_compile src/translator.py
          python -m py_compile src/prompts.py
